name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USER: root
  DB_NAME: actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install MySQL driver
        run: go get github.com/go-sql-driver/mysql

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Deploy
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
        run: |
          go run deploy.go
