name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USER: root
  DB_NAME: actions
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql: ['mysql:8', 'mysql:latest']

    services:
      mysql:
        image: ${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: example
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      
        
